version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  init-kafka-topic-client:
    image: bitnami/kafka:latest
    container_name: init-kafka-topic-client
    depends_on:
      - broker
    command: >
      bash -c '
        for t in $${TOPICS[@]}; do
           kafka-topics.sh --bootstrap-server $$BOOTSTRAP_ADDRESS --create --topic $$t --partitions 3
         done
        while sleep 60; do echo "nothing happened, just prevent container to stop. global search the whole project with this line to see where it outputs"; done
      '
    environment:
      BOOTSTRAP_ADDRESS: 'broker:29092'
      TOPICS: private-v1-order-execution-report public-v1-order-candlestick-minute public-v1-order-sliding-aggregate-twentyfourhour dev-com-gaplotech-mskdemo-ktor-data-aggregator-private-v1-store-order-candlestick-minute-repartition dev-com-gaplotech-mskdemo-ktor-data-aggregator-private-v1-store-order-candlestick-minute-changelog dev-com-gaplotech-mskdemo-ktor-data-aggregator-private-v1-store-order-sliding-aggregate-twentyfourhour-repartition dev-com-gaplotech-mskdemo-ktor-data-aggregator-private-v1-store-order-sliding-aggregate-twentyfourhour-changelog

  local-ktor-websocket:
    image: local-ktor-websocket:latest
    container_name: local-ktor-websocket
    ports:
      - "9000:9000"
    depends_on:
      - broker
    environment:
      BOOTSTRAP_ADDRESS: 'broker:29092'
      JAVA_TOOL_OPTIONS: -Dconfig.file=/app/resources/application.local.conf

  local-ktor-producer:
    image: local-ktor-producer:latest
    container_name: local-ktor-producer
    ports:
      - "8080:8080"
    depends_on:
      - broker
    environment:
      BOOTSTRAP_ADDRESS: 'broker:29092'
      JAVA_TOOL_OPTIONS: -Dconfig.file=/app/resources/application.local.conf

  local-ktor-data-aggregator:
    image: local-ktor-data-aggregator:latest
    container_name: local-ktor-data-aggregator
    depends_on:
      - broker
    environment:
      BOOTSTRAP_ADDRESS: 'broker:29092'
      JAVA_TOOL_OPTIONS: -Dconfig.file=/app/resources/application.local.conf